# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: ${{ matrix.jdk }}

    strategy:
      fail-fast: false
      matrix:
        jdk: [ 17 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    
    - name: Set up Python 3.
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify

    - name: Install dependencies
      run: | 
        pip install sphinx
        pip install sphinx-rtd-theme
        
    - name: Build documentation
      run: | 
        ./mvnw clean package
        java -jar phenopacket-tools-cli/target/phenopacket-tools-cli-0.4.5.jar examples
        mkdir gh-pages
        touch gh-pages/.nojekyll
        mkdir gh-pages/static
        cp -r families/ phenopackets/ cohorts/  gh-pages/static
        cd docs/ 
        sphinx-build -b html . _build
        cp -r _build/* ../gh-pages/

    - name: Deploy documentation.
      if: ${{ github.event_name == 'pull_request' }}
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        force: true
        folder: gh-pages


